site_name: linesranking
site_url: https://linesranking.readthedocs.io/en/latest/
site_author: ChrisLisbon & Dreamlone
repo_url: https://github.com/ChrisLisbon/QGIS_LinesRankingPlugin

nav:
    - Home: index.md
    - How to use:
          - 'Installation': 'usage/install.md'
          - 'Functionality review': 'usage/functionality_review.md'
          - 'River use case': 'usage/river_case.md'
          - 'Railways use case': 'usage/rails_case.md'
    - Theoretical issues:
          - 'Vector data': 'theoretical/vector_data.md'
          - 'Brief description': 'theoretical/algorithm.md'
    - 'About us':
          - 'Some info': 'about.md'
theme:
    name: readthedocs
    logo: https://raw.githubusercontent.com/ChrisLisbon/QGIS_LinesRankingPlugin/docs/images/logo_simple.png
