site_name: linesranking
site_url: https://linesranking.readthedocs.io/en/latest/
site_author: Dreamlone & ChrisLisbon
repo_url: https://github.com/ChrisLisbon/QGIS_LinesRankingPlugin

nav:
    - Home: index.md
    - How to use:
          - 'Installation': 'usage/install.md'
          - 'Functionality review': 'usage/functionality_review.md'
    - Theoretical issues:
          - 'Vector data': 'theoretical/vector_data.md'
          - 'HTTP connector': 'theoretical/2_http.md'
          - 'MQTT connector': 'theoretical/3_mqtt.md'
theme:
    name: readthedocs
    logo: https://raw.githubusercontent.com/ChrisLisbon/QGIS_LinesRankingPlugin/master/images/logo_simple.png
